name: "SVR"

exports: "SVR.js"

tags: [Native, Utilities]

web: "[ibolmo.com](http://ibolmo.com)"

description: "SVR (Separated Variable Reader)."

license: "[MIT License](http://mootools.net/license.txt)"

copyright: "&copy; [Olmo Maldonado](http://ibolmo.com/)"

authors: "[Olmo Maldonado](http://ibolmo.com)"

sources: ["Source/SVR.js"]
